### ISSUE TITLE
Vue.draggable is not working on computed variables 

### ISSUE THREAD

**Issue by followingjoneses** [aweb-pj/front-end#17]
I was trying using Vue.draggble to solve the 'drag and sort' problem but it turns out a misfunction on computed variable 'exercises'.

**Comment by jt-wang** [comment]
[官方示例](https://github.com/SortableJS/Vue.Draggable#with-vuex)里面可以用在 computed property 上，你 pull 我最新的 master 之后，把你的 draggable 相关代码加上去 push 到 zhuoli 分支好了，我来看一下。

**Comment by followingjoneses** [comment]
我找到解决方法了，是Vuex的问题
