### ISSUE TITLE
切换MindMap

### ISSUE THREAD

**Issue by followingjoneses** [aweb-pj/front-end#22]
对于一个新建的treeId来说，由于返回的是空对象，所以要用jsMind.show(options)的方法来创建一个初始mindmap，但是该方法会在原来的mindmap下方新建一个mindmap，而不是覆盖原来的mindmap。

期望：
覆盖原来的mindmap。

进展：
即使使用jm._reset，也只会消除原来的mindmap，新的mindmap会出现在原来区域的下方。

**Comment by jt-wang** [comment]
pr #23
