### ISSUE TITLE
无法显示 el-dialog

### ISSUE THREAD

**Issue by jt-wang** [aweb-pj/front-end#6]
## 问题
按照 [elements 官网文档](http://element.eleme.io/#/zh-CN/component/dialog)，在 `Material.vue` 里添加同样代码，点击按钮之后没有任何显示，同时，没有报错。

## 期望
<img width="537" alt="screen shot 2017-05-14 at 21 24 47" src="https://cloud.githubusercontent.com/assets/7776499/26034221/ff3413c4-38eb-11e7-80a8-b0671518ca03.png">

点击`打开嵌套表单的 Dialog 按钮`后，应该弹出如官网文档所示的对话框。

## 尝试 debug
通过 chrome 调试台找到该 div 后，发现其 `display: none;`。把该项去掉之后，能够显示如下：
<img width="1028" alt="screen shot 2017-05-14 at 21 28 30" src="https://cloud.githubusercontent.com/assets/7776499/26034235/52799d10-38ec-11e7-9ddb-228c030c01e2.png">

但是，显然**表格里的任何内容都没有正常显示**，且不是模态的。即任何数据绑定都没有生效。

## 与成功的代码比较

尝试单独起一个项目，里面的根 view 就是官网的示例，则能够正常运行。推测是 elements 的 el-tab/el-col 导致的问题。但是这种推测不能解释 “为什么在把 `display:none;` 改掉之后，对话框里的表格仍然没有正常显示”。

**Comment by followingjoneses** [comment]
element-ui版本为1.2.9，官网默认教程版本为1.3.3。
