### ISSUE TITLE
对思维导图的操作

### ISSUE THREAD

**Issue by jt-wang** [aweb-pj/front-end#7]
[编辑节点](https://github.com/hizzgdev/jsmind/blob/master/docs/zh/3.operation.md#34-编辑节点)
[设置样式](https://github.com/hizzgdev/jsmind/blob/master/docs/zh/3.operation.md#35-设置样式)

基本上就是把上述文档的选项放到顶部菜单栏里就行。新增，删除，改颜色，选中、取消选中等等。

**Comment by followingjoneses** [comment]
简单写了一些，现在大致存在以下一些问题：
1. - [x] 添加结点时只能添加同层结点，before的意思为插入到选中结点之前，而不是成为它的父节点。同理，after为插入到选中结点之后，而不是成为它的子节点。这个前后直观来看是纵向的，而不是横向的。
2. - [x] 对结点修改颜色没有变化，console中显示node的background-color确实有变化，但页面上没有变化。与文档上所说不符。
3. - [ ] 考虑用一个调色板解决修改颜色的问题，但没找到符合ES6语法的库。
4. - [ ] 代码没有做优化。

**Comment by jt-wang** [comment]
## 问题 1
已 fix 在 master 分支。
<del>在修复过程中发现新的 bug https://github.com/aweb-pj/front-end/issues/8</del> (已修复 #8)


## 问题 2
已fix 在 master 分支。
**原因**: jsmind.js 里检查 background-color 部分有单词拼写错误。

## 问题 3
还没看，估计有 jQuery 相关的库。这个不着急，可以先给他几个固定的颜色选项。

## 问题 4
等20号之后我来重构好了。

**Comment by jt-wang** [comment]
问题3 和 问题4 影响不大，先 close 掉这个 issue 了。
