### ISSUE TITLE
用一个调色板解决修改颜色的问题

### ISSUE THREAD

**Issue by jt-wang** [aweb-pj/front-end#9]

**Comment by jt-wang** [comment]
@jzlshitian 参考 [做一个调色板](http://www.yi-jy.com/2014/12/22/%E5%81%9A%E4%B8%80%E4%B8%AA%E8%B0%83%E8%89%B2%E6%9D%BF/?xupmry=b4t7x1)，似乎可以用 html5 的 新 type

**Comment by followingjoneses** [comment]
Use vue-color
